### ISSUE TITLE
Cannot find module lib/forkable.js

### ISSUE THREAD

**Issue by Mexassi** [apiaryio/pitboss#20]
I am writing an electron app using this module. The electron-builder does not correctly resolve the path for the local module `forkable.js`.

I had a peek at the code and noticed that the absolute path to forkable.js is resolved with `path.join(__dirname, '../lib/forkable.js');`. I am wondering what is the reason for not using `require.resolve('../lib/forkable.js')`? 

My understanding is `require.resolve` uses module-relative paths to resolve the file path for that module which would work better when using a module bundler. Would you consider updating your code using `require.resolve`? 

If not could you explain why path.join is a better approach here?

**Comment by kuba-kubula** [comment]
@Mexassi Hello and please accept my apology for the wait: there is new `pitboss-ng` released as version `2.0.1` using require.resolve

Closed by https://github.com/apiaryio/pitboss/commit/794add6d90c178b6fd901aa75d156c427dd3b246
