### ISSUE TITLE
Modules loading documentation

### ISSUE THREAD

**Issue by netmilk** [apiaryio/pitboss#4]
Hi @tu1ly, 
  Do I understand correctly, that in this fork I'm able to load arbitrary modules into the Pitboss scope? Can you please add an example for this functionality to the Readme?
Thanks & cheers!
Adam

**Comment by kuba-kubula** [comment]
The present README contains examples for libraries loading. See https://github.com/apiaryio/pitboss#a-module-for-running-untrusted-code
